networks:
  wmpdv_network:
    driver: bridge
services:
  api:
    build: .
    networks:
      - wmpdv_network
    ports:
      - "8000:8000"
  db:
    image: postgres:14.2-alpine
    environment:
      - POSTGRES_DB=wmpdv_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    networks:
      - wmpdv_network

volumes:
  postgres_data: